version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=interview
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  server:
    build: ./service-indriver
    restart: on-failure
    ports:
      - '8080:8080'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  
